services:
  - type: web
    name: api-horarios
    env: docker
    plan: free
    buildCommand: dotnet build
    startCommand: dotnet App-horarios-BackEnd.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Host=metro.proxy.rlwy.net;Port=41551;Database=railway;Username=postgres;Password=GsSwLEymrzGVkhVUPoYczvOvFQoQnERb;SSL Mode=Require