services:
  - type: web
    name: api-horarios
    env: docker
    plan: free
    autoDeploy: true
    branch: main
    rootDir: App-horarios-BackEnd
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
        
      - key: ConnectionStrings__DefaultConnection
        value: Host=metro.proxy.rlwy.net;Port=41551;Database=railway;Username=postgres;Password=GsSwLEymrzGVkhVUPoYczvOvFQoQnERb;SSL Mode=Require
